name: Glitch Keep-Alive

on:
  schedule:
    # This cron job is set to run every minute
    - cron: '* * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Glitch App
        run: curl -m 10 https://drink-tracker.glitch.me
